server:
  port: 8080  # Proxy Gateway runs on port 8080

spring:
  application:
    name: proxy-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service  # ✅ Removed extra hyphen
          uri: lb://USER-SERVICE  # Load balanced to user-service
          predicates:
            - Path=/user/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE  # Load balanced to product-service
          predicates:
            - Path=/product/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # ✅ Removed comma
